### ISSUE TITLE
Crash when moving window under KDE

### ISSUE THREAD

**Issue by deadw00d** [deadw00d/AROS#81]
Intuition.library crashes when trying to drag window under KDE running on Ubuntu 22.10. This is not happening under Gnome on Ubuntu 22.10. 

Backtrace:

#0  0x00007ffff731e981 in SendClientMessageActive (win=0x0, IntuitionBase=0x7ffff0046e40)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/AROS/arch/all-runtimelinux/intuition/intuition_x.c:202
#1  0x00007ffff72a7bfb in Intuition_75_ActivateWindow (window=0x0)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/AROS/rom/intuition/./activatewindow.c:88
#2  0x00007ffff72dba0a in __inline_Intuition_ActivateWindow (__arg1=0x0, __IntuitionBase=0x7ffff0046e40)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/alt-runtimelinux-x86_64-d/bin/runtimelinux-x86_64/AROS/Development/include/inline/intuition.h:1128
#3  0x00007ffff72e1199 in IntuiInputHandler (oldchain=0x7fffec001850, iihdata=0x7ffff0098f30)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/AROS/rom/intuition/./inputhandler.c:2145
#4  0x00007ffff6ff86db in ForwardQueuedEvents (InputDevice=0x7ffff0039a60)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/AROS/rom/devs/input/./processevents.c:126
#5  0x00007ffff6ff9dad in ProcessEvents (InputDevice=0x7ffff0039a60)
    at /ssd/deadwood/repo-github-dd-alt-runtimelinux/AROS/rom/devs/input/./processevents.c:570

**Comment by deadw00d** [comment]
Fixed in 7008bba81261f39fba8de289dba4fe9d24b35a02
